"""empty message

Revision ID: 0ca8950c966c
Revises: 48a06640a1ee
Create Date: 2025-02-10 13:48:35.104813

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0ca8950c966c'
down_revision = '48a06640a1ee'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cancellation_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('holder_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    with op.batch_alter_table('unqualified_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('unqualified_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('holder_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    with op.batch_alter_table('cancellation_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
