"""empty message

Revision ID: 169558b79347
Revises: 6c1f42164a63
Create Date: 2025-02-09 20:55:01.278356

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '169558b79347'
down_revision = '6c1f42164a63'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('avatar')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('avatar', sa.VARCHAR(length=200), autoincrement=False, nullable=True))

    # ### end Alembic commands ###
