"""empty message

Revision ID: 48a06640a1ee
Revises: 169558b79347
Create Date: 2025-02-09 23:57:13.115239

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48a06640a1ee'
down_revision = '169558b79347'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=20),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('operator_db', schema=None) as batch_op:
        batch_op.alter_column('oid',
               existing_type=sa.String(length=20),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
